source $HOME/.config/nvim/vim-plug/plugins.vim
source $HOME/.config/nvim/general/settings.vim
source $HOME/.config/nvim/general/augroups.vim
source $HOME/.config/nvim/general/keys.vim
source $HOME/.config/nvim/general/snippets.vim
source $HOME/.config/nvim/general/vimtex-settings.vim
source $HOME/.config/nvim/general/vimwiki-settings.vim
source $HOME/.config/nvim/general/theme.vim
source $HOME/.config/nvim/general/coc-settings.vim
